// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portiforce.SimpleAssetAssistant.Infrastructure.EF.DbContexts;

#nullable disable

namespace Portiforce.SimpleAssetAssistant.Infrastructure.EF.Migrations
{
    [DbContext(typeof(AssetAssistantDbContext))]
    [Migration("20260201232539_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pf")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Activities.AssetActivityBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PlatformAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ExternalMetadata", "Portiforce.SimpleAssetAssistant.Core.Activities.Models.Activities.AssetActivityBase.ExternalMetadata#ExternalMetadata", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ExternalId")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ExternalId");

                            b1.Property<string>("Fingerprint")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Fingerprint");

                            b1.Property<string>("Notes")
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("ExternalNotes");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ExternalSource");
                        });

                    b.HasKey("Id");

                    b.HasIndex("PlatformAccountId", "OccurredAt", "Id")
                        .HasDatabaseName("IX_Activity_PlatformAccount_OccurredAt_Id");

                    b.ToTable("Activities", "ledger");

                    b.HasDiscriminator<byte>("Kind");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Legs.AssetMovementLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Allocation")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(38, 18)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Direction")
                        .HasColumnType("tinyint");

                    b.Property<string>("InstrumentKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("IX_Leg_ActivityId");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("IX_Leg_AssetId");

                    b.ToTable("ActivityLegs", "ledger");
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Assets.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("NativeDecimals")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("State")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_Asset_State");

                    b.HasIndex("Code", "Kind")
                        .IsUnique()
                        .HasDatabaseName("UX_Asset_Code_Kind");

                    b.ToTable("Assets", "core");
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Assets.Models.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("State")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Platform_Code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Platform_Name");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_Platform_State");

                    b.ToTable("Platforms", "core");
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Assets.Models.PlatformAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExternalAccountId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExternalUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("State")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("TenantId", "AccountId")
                        .HasDatabaseName("IX_PlatformAccount_Tenant_Account");

                    b.HasIndex("TenantId", "PlatformId")
                        .HasDatabaseName("IX_PlatformAccount_Tenant_Platform");

                    b.HasIndex("TenantId", "AccountId", "PlatformId")
                        .IsUnique()
                        .HasDatabaseName("UX_PlatformAccount_Tenant_Account_Platform");

                    b.ToTable("PlatformAccounts", "core");
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Identity.Models.Auth.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<byte>("Provider")
                        .HasColumnType("tinyint");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TenantId");

                    b.HasIndex("Provider", "ProviderSubject")
                        .IsUnique()
                        .HasDatabaseName("UX_ExternalIdentity_Provider_ExternalId");

                    b.ToTable("ExternalIdentities", "auth");
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Identity.Models.Auth.PasskeyCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("SignatureCounter")
                        .HasColumnType("bigint");

                    b.Property<string>("UserHandle")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CredentialId")
                        .IsUnique()
                        .HasDatabaseName("UX_PasskeyCredential_CredentialId");

                    b.ToTable("PassKeyCredentials", "auth");
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Identity.Models.Client.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrandName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("DomainPrefix")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Plan")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("State")
                        .HasColumnType("tinyint");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Settings", "Portiforce.SimpleAssetAssistant.Core.Identity.Models.Client.Tenant.Settings#TenantSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Defaults", "Portiforce.SimpleAssetAssistant.Core.Identity.Models.Client.Tenant.Settings#TenantSettings.Defaults#TenantDefaults", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("DefaultCurrency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("Defaults_DefaultCurrency");

                                    b2.Property<string>("DefaultLocale")
                                        .IsRequired()
                                        .HasMaxLength(6)
                                        .HasColumnType("nvarchar(6)")
                                        .HasColumnName("Defaults_DefaultLocale");

                                    b2.Property<string>("DefaultTimeZoneId")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("nvarchar(64)")
                                        .HasColumnName("Defaults_DefaultTimeZone");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Import", "Portiforce.SimpleAssetAssistant.Core.Identity.Models.Client.Tenant.Settings#TenantSettings.Import#TenantImportSettings", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("MaxFileSizeMb")
                                        .HasColumnType("int")
                                        .HasColumnName("Import_MaxFileSizeMb");

                                    b2.Property<int>("MaxRowsPerImport")
                                        .HasColumnType("int")
                                        .HasColumnName("Import_MaxRows");

                                    b2.Property<bool>("RequireReviewBeforeProcessing")
                                        .HasColumnType("bit")
                                        .HasColumnName("Import_RequireReview");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Retention", "Portiforce.SimpleAssetAssistant.Core.Identity.Models.Client.Tenant.Settings#TenantSettings.Retention#TenantRetentionSettings", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("DeletedDataRetentionDays")
                                        .HasColumnType("int")
                                        .HasColumnName("Retention_DeletedDays");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Security", "Portiforce.SimpleAssetAssistant.Core.Identity.Models.Client.Tenant.Settings#TenantSettings.Security#TenantSecuritySettings", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<bool>("EnforceTwoFactor")
                                        .HasColumnType("bit")
                                        .HasColumnName("Security_EnforceTwoFactor");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Tenant_Code");

                    b.HasIndex("DomainPrefix")
                        .IsUnique()
                        .HasDatabaseName("UX_Tenant_DomainPrefix")
                        .HasFilter("[DomainPrefix] IS NOT NULL");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_Tenant_State");

                    b.ToTable("Tenants", "core");
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Identity.Models.Client.TenantRestrictedAsset", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantId", "AssetId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_TenantRestrictedAsset_TenantId");

                    b.ToTable("TenantRestrictedAssets", "core");
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Identity.Models.Client.TenantRestrictedPlatform", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantId", "PlatformId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_TenantRestrictedPlatform_TenantId");

                    b.ToTable("TenantRestrictedPlatforms", "core");
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Identity.Models.Profile.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("State")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Tier")
                        .HasColumnType("tinyint");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Contact", "Portiforce.SimpleAssetAssistant.Core.Identity.Models.Profile.Account.Contact#ContactInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("BackupEmail")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ContactBackupEmail");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ContactEmail");

                            b1.Property<string>("Phone")
                                .HasMaxLength(15)
                                .HasColumnType("nvarchar(15)")
                                .HasColumnName("ContactPhone");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Settings", "Portiforce.SimpleAssetAssistant.Core.Identity.Models.Profile.Account.Settings#AccountSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("DefaultCurrency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Settings_DefaultFiatCurrency");

                            b1.Property<string>("Locale")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("nvarchar(6)")
                                .HasColumnName("Settings_Locale");

                            b1.Property<string>("TimeZoneId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Settings_TimeZone");

                            b1.Property<bool>("TwoFactorPreferred")
                                .HasColumnType("bit")
                                .HasColumnName("TwoFactorPreferred");
                        });

                    b.HasKey("Id");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_Account_State");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Account_TenantId");

                    b.ToTable("Accounts", "core");
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Activities.BurnActivity", b =>
                {
                    b.HasBaseType("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Activities.AssetActivityBase");

                    b.Property<byte>("Reason")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("tinyint");

                    b.HasDiscriminator().HasValue((byte)5);
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Activities.ExchangeActivity", b =>
                {
                    b.HasBaseType("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Activities.AssetActivityBase");

                    b.Property<byte>("CompletionType")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("tinyint");

                    b.Property<byte>("ExchangeType")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Reason")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("tinyint");

                    b.HasDiscriminator().HasValue((byte)2);
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Activities.IncomeActivity", b =>
                {
                    b.HasBaseType("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Activities.AssetActivityBase");

                    b.Property<byte>("Reason")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("tinyint");

                    b.HasDiscriminator().HasValue((byte)4);
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Activities.ServiceActivity", b =>
                {
                    b.HasBaseType("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Activities.AssetActivityBase");

                    b.Property<byte>("Reason")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("tinyint");

                    b.Property<byte>("ServiceType")
                        .HasColumnType("tinyint");

                    b.HasDiscriminator().HasValue((byte)6);
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Activities.TradeActivity", b =>
                {
                    b.HasBaseType("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Activities.AssetActivityBase");

                    b.Property<byte>("CompletionType")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("tinyint");

                    b.Property<byte>("ExecutionType")
                        .HasColumnType("tinyint");

                    b.Property<byte>("MarketKind")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Reason")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("tinyint");

                    b.HasDiscriminator().HasValue((byte)1);
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Activities.TransferActivity", b =>
                {
                    b.HasBaseType("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Activities.AssetActivityBase");

                    b.Property<string>("Counterparty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Direction")
                        .HasColumnType("tinyint");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("TransferKind")
                        .HasColumnType("tinyint");

                    b.HasDiscriminator().HasValue((byte)3);
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Activities.UserCorrectionActivity", b =>
                {
                    b.HasBaseType("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Activities.AssetActivityBase");

                    b.Property<byte>("Reason")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("tinyint");

                    b.HasDiscriminator().HasValue((byte)7);
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Activities.AssetActivityBase", b =>
                {
                    b.HasOne("Portiforce.SimpleAssetAssistant.Core.Assets.Models.PlatformAccount", null)
                        .WithMany()
                        .HasForeignKey("PlatformAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Legs.AssetMovementLeg", b =>
                {
                    b.HasOne("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Activities.AssetActivityBase", null)
                        .WithMany("Legs")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portiforce.SimpleAssetAssistant.Core.Assets.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Assets.Models.PlatformAccount", b =>
                {
                    b.HasOne("Portiforce.SimpleAssetAssistant.Core.Identity.Models.Profile.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Portiforce.SimpleAssetAssistant.Core.Assets.Models.Platform", null)
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Portiforce.SimpleAssetAssistant.Core.Identity.Models.Client.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Identity.Models.Auth.ExternalIdentity", b =>
                {
                    b.HasOne("Portiforce.SimpleAssetAssistant.Core.Identity.Models.Profile.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portiforce.SimpleAssetAssistant.Core.Identity.Models.Client.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Identity.Models.Auth.PasskeyCredential", b =>
                {
                    b.HasOne("Portiforce.SimpleAssetAssistant.Core.Identity.Models.Profile.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Identity.Models.Client.TenantRestrictedAsset", b =>
                {
                    b.HasOne("Portiforce.SimpleAssetAssistant.Core.Identity.Models.Client.Tenant", null)
                        .WithMany("RestrictedAssets")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Identity.Models.Client.TenantRestrictedPlatform", b =>
                {
                    b.HasOne("Portiforce.SimpleAssetAssistant.Core.Identity.Models.Client.Tenant", null)
                        .WithMany("RestrictedPlatforms")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Identity.Models.Profile.Account", b =>
                {
                    b.HasOne("Portiforce.SimpleAssetAssistant.Core.Identity.Models.Client.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Activities.TradeActivity", b =>
                {
                    b.OwnsOne("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Futures.FuturesDescriptor", "Futures", b1 =>
                        {
                            b1.Property<Guid>("TradeActivityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BaseAssetCode")
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("Futures_BaseAssetCode");

                            b1.Property<byte>("ContractKind")
                                .HasColumnType("tinyint")
                                .HasColumnName("Futures_ContractKind");

                            b1.Property<string>("InstrumentKey")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Futures_InstrumentKey");

                            b1.Property<byte?>("PositionEffect")
                                .HasColumnType("tinyint")
                                .HasColumnName("Futures_PositionEffect");

                            b1.Property<string>("QuoteAssetCode")
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("Futures_QuoteAssetCode");

                            b1.HasKey("TradeActivityId");

                            b1.ToTable("Activities", "ledger");

                            b1.WithOwner()
                                .HasForeignKey("TradeActivityId");
                        });

                    b.Navigation("Futures");
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Activities.Models.Activities.AssetActivityBase", b =>
                {
                    b.Navigation("Legs");
                });

            modelBuilder.Entity("Portiforce.SimpleAssetAssistant.Core.Identity.Models.Client.Tenant", b =>
                {
                    b.Navigation("RestrictedAssets");

                    b.Navigation("RestrictedPlatforms");
                });
#pragma warning restore 612, 618
        }
    }
}
