using Portiforce.SAA.Core.Assets.Enums;
using Portiforce.SAA.Core.Assets.Models;
using Portiforce.SAA.Core.Primitives;
using Portiforce.SAA.Core.StaticResources;

namespace Portiforce.SAA.Infrastructure.EF.DataPopulation.Seeders;

public static class AssetDataSeeder
{
	public static List<Asset> BuildAssets()
	{
		var assets = new List<Asset>();

		// ---------------------------------------------------------
		// 1. STOCKS (50 Total: EntityConstraints.Domain.Asset.NativeDecimalsAvgLength Requested + 40 Top Market Cap)
		// ---------------------------------------------------------
		var stockData = new List<(string Code, string Name)>
		{
			("AMZN", "Amazon.com Inc"),
			("MSFT", "Microsoft Corporation"),
			("AAPL", "Apple Inc"),
			("GOOGL", "Alphabet Inc Class A"),
			("BRK.B", "Berkshire Hathaway Inc Class B"),
			("IONQ", "IonQ Inc"),
			("RGTI", "Rigetti Computing Inc"),
			("AVGO", "Broadcom Inc"),
			("NFLX", "Netflix Inc"),
			("KO", "Coca-Cola Company"),

			// Top Market Cap Fillers
			 ("NVDA", "NVIDIA Corporation"),
			("META", "Meta Platforms Inc"),
			("TSLA", "Tesla Inc"),
			("LLY", "Eli Lilly and Company"),
			("V", "Visa Inc"),
			("UNH", "UnitedHealth Group Incorporated"),
			("XOM", "Exxon Mobil Corporation"),
			("JPM", "JPMorgan Chase & Co"),
			("JNJ", "Johnson & Johnson"),
			("MA", "Mastercard Incorporated"),
			("PG", "Procter & Gamble Company"),
			("HD", "Home Depot Inc"),
			("MRK", "Merck & Co Inc"),
			("COST", "Costco Wholesale Corporation"),
			("ABBV", "AbbVie Inc"),
			("CVX", "Chevron Corporation"),
			("AMD", "Advanced Micro Devices Inc"),
			("CRM", "Salesforce Inc"),
			("PEP", "PepsiCo Inc"),
			("BAC", "Bank of America Corporation"),
			("ACN", "Accenture plc"),
			("MCD", "McDonald's Corporation"),
			("CSCO", "Cisco Systems Inc"),
			("LIN", "Linde plc"),
			("ABT", "Abbott Laboratories"),
			("TMO", "Thermo Fisher Scientific Inc"),
			("DIS", "Walt Disney Company"),
			("WMT", "Walmart Inc"),
			("CMCSA", "Comcast Corporation"),
			("PFE", "Pfizer Inc"),
			("NKE", "NIKE Inc"),
			("INTU", "Intuit Inc"),
			("ORCL", "Oracle Corporation"),
			("WELL", "Welltower Inc"),
			("VZ", "Verizon Communications Inc"),
			("DHR", "Danaher Corporation"),
			("TXN", "Texas Instruments Incorporated"),
			("PM", "Philip Morris International Inc"),
			("UNP", "Union Pacific Corporation"),
			("INTC", "Intel Corporation")
		};

		foreach (var stock in stockData)
		{
			assets.Add(Asset.Create(
				AssetCode.Create(stock.Code),
				AssetKind.Stock,
				AssetLifecycleState.Active,
				stock.Name,
				nativeDecimals: 2
			));
		}

		// ---------------------------------------------------------
		// 2. CRYPTOCURRENCIES (Top 200)
		// ---------------------------------------------------------
		// Note: Native decimals vary (BTC=EntityConstraints.Domain.Asset.NativeDecimalsAvgLength, ETH=EntityConstraints.Domain.Asset.NativeDecimalsMaxLength)
		var cryptoData = new List<(string Code, string Name, byte Decimals)>
		{
			("BTC", "Bitcoin", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("ETH", "Ethereum", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("USDT", "Tether", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("BNB", "BNB", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("SOL", "Solana", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("USDC", "USDC", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("XRP", "XRP", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("DOGE", "Dogecoin", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("TON", "Toncoin", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("ADA", "Cardano", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("AVAX", "Avalanche", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("SHIB", "Shiba Inu", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("DOT", "Polkadot", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("LINK", "Chainlink", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("BCH", "Bitcoin Cash", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("TRX", "TRON", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("LTC", "Litecoin", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("MATIC", "Polygon", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("NEAR", "NEAR Protocol", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("LEO", "UNUS SED LEO", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("DAI", "Dai", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("UNI", "Uniswap", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("ICP", "Internet Computer", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("ETC", "Ethereum Classic", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("APT", "Aptos", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("XLM", "Stellar", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("OKB", "OKB", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("MNT", "Mantle", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("HBAR", "Hedera", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("FIL", "Filecoin", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("ATOM", "Cosmos", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("ARB", "Arbitrum", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("IMX", "Immutable", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("STX", "Stacks", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("KAS", "Kaspa", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("VET", "VeChain", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("CRO", "Cronos", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("MKR", "Maker", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("GRT", "The Graph", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("XMR", "Monero", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("RNDR", "Render", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("OP", "Optimism", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("EGLD", "MultiversX", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("INJ", "Injective", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("AAVE", "Aave", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("THETA", "Theta Network", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("BSV", "Bitcoin SV", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("ALGO", "Algorand", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("MINA", "Mina", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("TIA", "Celestia", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("FLOW", "Flow", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("SNX", "Synthetix", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("AXS", "Axie Infinity", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("SAND", "The Sandbox", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("KAVA", "Kava", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("XTZ", "Tezos", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("MANA", "Decentraland", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("EOS", "EOS", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("IOTA", "IOTA", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("NEO", "Neo", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("CHZ", "Chiliz", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("GALA", "Gala", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("KCS", "KuCoin Token", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("XEC", "eCash", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("KLAY", "Klaytn", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("FXS", "Frax Share", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("LDO", "Lido DAO", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("QNT", "Quant", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("CRV", "Curve DAO Token", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("PAXG", "PAX Gold", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("USDD", "USDD", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("TUSD", "TrueUSD", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("BGB", "Bitget Token", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("FTM", "Fantom", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("CAKE", "PancakeSwap", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("HT", "Huobi Token", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("ZEC", "Zcash", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("MIOTA", "IOTA", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("XEM", "NEM", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("GNO", "Gnosis", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("BTT", "BitTorrent", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("GAS", "Gas", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("1INCH", "1inch Network", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("CVX", "Convex Finance", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("COMP", "Compound", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("BAT", "Basic Attention Token", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("ZIL", "Zilliqa", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("QTUM", "Qtum", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("LRC", "Loopring", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("TWT", "Trust Wallet Token", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("DCR", "Decred", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("ENJ", "Enjin Coin", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("RVN", "Ravencoin", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("DASH", "Dash", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("NEXO", "Nexo", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("YFI", "yearn.finance", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("ANKR", "Ankr", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("GLM", "Golem", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("SC", "Siacoin", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("ONT", "Ontology", EntityConstraints.Domain.Asset.NativeDecimalsZeroLength),
			("ZRX", "0x", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("IOST", "IOST", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("ICX", "ICON", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("WAVES", "Waves", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("BNT", "Bancor", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("FLR", "Flare", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("KSM", "Kusama", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("ONE", "Harmony", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("SXP", "Solar", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("DGB", "DigiByte", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("CKB", "Nervos Network", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("BAND", "Band Protocol", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("STORJ", "Storj", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("LSK", "Lisk", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("DENT", "Dent", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("AR", "Arweave", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("OCEAN", "Ocean Protocol", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("JST", "JUST", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("WRX", "WazirX", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("POLY", "Polymath", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("POWR", "Power Ledger", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("SNT", "Status", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("STEEM", "Steem", EntityConstraints.Domain.Asset.NativeDecimalsFiatLength),
			("MED", "MediBloc", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("STPT", "STP", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("STRAX", "Stratis", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("ADX", "Ambire AdEx", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("MTL", "Metal DAO", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("XVG", "Verge", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("VTHO", "VeThor Token", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("LOOM", "Loom Network", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("PROM", "Prom", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("RLC", "iExec RLC", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("SYS", "Syscoin", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("NMR", "Numeraire", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("HIVE", "Hive", EntityConstraints.Domain.Asset.NativeDecimalsFiatLength),
			("IQ", "IQ", EntityConstraints.Domain.Asset.NativeDecimalsFiatLength),
			("DOCK", "Dock", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("HIFI", "Hifi Finance", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("AKRO", "Akropolis", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("OXT", "Orchid", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("CVC", "Civic", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("STMX", "StormX", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("PUNDIX", "Pundi X (New)", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("MOC", "Moss Coin", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("PHA", "Phala Network", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("FUN", "FUNToken", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("REQ", "Request", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("SUN", "Sun (New)", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("NKN", "NKN", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("BAKE", "BakeryToken", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("TKO", "Tokocrypto", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("COS", "Contentos", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("WAXP", "WAX", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("PERP", "Perpetual Protocol", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("TRB", "Tellor", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("KEY", "SelfKey", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("WAN", "Wanchain", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("IRIS", "IRISnet", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("KMD", "Komodo", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("ARDR", "Ardor", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("MBL", "MovieBloc", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("CTXC", "Cortex", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("DUSK", "Dusk", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("COCOS", "COS", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("POND", "Marlin", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("HFT", "Hashflow", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("ACH", "Alchemy Pay", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("AMP", "Amp", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("PLA", "PlayDapp", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("FIDA", "Bonfida", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("RAY", "Raydium", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("SRM", "Serum", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("MNGO", "Mango", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("ORCA", "Orca", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("SBR", "Saber", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("MER", "Mercurial", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("PORT", "Port Finance", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("LARI", "Larix", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("JET", "Jet", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("SLND", "Solend", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("MNDE", "Marinade", EntityConstraints.Domain.Asset.NativeDecimalsMinLength),
			("SAMO", "Samoyedcoin", EntityConstraints.Domain.Asset.NativeDecimalsAvgLength),
			("C98", "Coin98", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("MC", "Merit Circle", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("PYR", "Vulcan Forged", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("ILV", "Illuvium", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("GHST", "Aavegotchi", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength),
			("RARE", "SuperRare", EntityConstraints.Domain.Asset.NativeDecimalsMaxLength)
		};

		foreach (var crypto in cryptoData)
		{
			assets.Add(
				Asset.Create(
					AssetCode.Create(crypto.Code),
					AssetKind.Crypto,
					AssetLifecycleState.Active,
					crypto.Name,
					nativeDecimals: crypto.Decimals
			));
		}

		return assets;
	}
}
