//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portiforce.SAA.Web.Client.Resources.Pages.Tenant.Admin.InviteFlow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Invites {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Invites() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portiforce.SAA.Web.Client.Resources.Pages.Tenant.Admin.InviteFlow.Invites", typeof(Invites).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any option.
        /// </summary>
        internal static string AccountFilterAny {
            get {
                return ResourceManager.GetString("AccountFilterAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account filter.
        /// </summary>
        internal static string AccountFilterLabel {
            get {
                return ResourceManager.GetString("AccountFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only with account.
        /// </summary>
        internal static string AccountFilterOnlyWithAccount {
            get {
                return ResourceManager.GetString("AccountFilterOnlyWithAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only without account.
        /// </summary>
        internal static string AccountFilterOnlyWithoutAccount {
            get {
                return ResourceManager.GetString("AccountFilterOnlyWithoutAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Channels.
        /// </summary>
        internal static string AllChannels {
            get {
                return ResourceManager.GetString("AllChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Statuses.
        /// </summary>
        internal static string AllStatuses {
            get {
                return ResourceManager.GetString("AllStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        internal static string ButtonResend {
            get {
                return ResourceManager.GetString("ButtonResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke.
        /// </summary>
        internal static string ButtonRevoke {
            get {
                return ResourceManager.GetString("ButtonRevoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple ID.
        /// </summary>
        internal static string ChannelAppleId {
            get {
                return ResourceManager.GetString("ChannelAppleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ChannelEmail {
            get {
                return ResourceManager.GetString("ChannelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        internal static string ChannelsLabel {
            get {
                return ResourceManager.GetString("ChannelsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram.
        /// </summary>
        internal static string ChannelTelegram {
            get {
                return ResourceManager.GetString("ChannelTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to revoke this invite?.
        /// </summary>
        internal static string ConfirmRevokeInvite {
            get {
                return ResourceManager.GetString("ConfirmRevokeInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load invites: {0}.
        /// </summary>
        internal static string CouldNotLoadInvites {
            get {
                return ResourceManager.GetString("CouldNotLoadInvites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not revoke invite: {0}.
        /// </summary>
        internal static string CouldNotRevokeInvite {
            get {
                return ResourceManager.GetString("CouldNotRevokeInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string GridChannel {
            get {
                return ResourceManager.GetString("GridChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string GridRole {
            get {
                return ResourceManager.GetString("GridRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string GridStatus {
            get {
                return ResourceManager.GetString("GridStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string GridTarget {
            get {
                return ResourceManager.GetString("GridTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite User.
        /// </summary>
        internal static string InviteUser {
            get {
                return ResourceManager.GetString("InviteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No invites found matching your criteria..
        /// </summary>
        internal static string NoInvitesFound {
            get {
                return ResourceManager.GetString("NoInvitesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Invites.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search targets.
        /// </summary>
        internal static string SearchTargetsLabel {
            get {
                return ResourceManager.GetString("SearchTargetsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search targets....
        /// </summary>
        internal static string SearchTargetsPlaceholder {
            get {
                return ResourceManager.GetString("SearchTargetsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string StatusAccepted {
            get {
                return ResourceManager.GetString("StatusAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        internal static string StatusDeclined {
            get {
                return ResourceManager.GetString("StatusDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statuses.
        /// </summary>
        internal static string StatusesLabel {
            get {
                return ResourceManager.GetString("StatusesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        internal static string StatusExpired {
            get {
                return ResourceManager.GetString("StatusExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string StatusFailed {
            get {
                return ResourceManager.GetString("StatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string StatusPending {
            get {
                return ResourceManager.GetString("StatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoked.
        /// </summary>
        internal static string StatusRevoked {
            get {
                return ResourceManager.GetString("StatusRevoked", resourceCulture);
            }
        }
    }
}
