//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portiforce.SAA.Web.Client.Resources.Pages.Tenant.Admin.InviteFlow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Invites {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Invites() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portiforce.SAA.Web.Client.Resources.Pages.Tenant.Admin.InviteFlow.Invites", typeof(Invites).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite User.
        /// </summary>
        internal static string ActionInviteUser {
            get {
                return ResourceManager.GetString("ActionInviteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to revoke this invite?.
        /// </summary>
        internal static string ConfirmRevokeInvite {
            get {
                return ResourceManager.GetString("ConfirmRevokeInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string GridHeaderChannel {
            get {
                return ResourceManager.GetString("GridHeaderChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string GridHeaderRole {
            get {
                return ResourceManager.GetString("GridHeaderRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string GridHeaderStatus {
            get {
                return ResourceManager.GetString("GridHeaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string GridHeaderTarget {
            get {
                return ResourceManager.GetString("GridHeaderTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account filter.
        /// </summary>
        internal static string LabelAccountFilter {
            get {
                return ResourceManager.GetString("LabelAccountFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        internal static string LabelChannels {
            get {
                return ResourceManager.GetString("LabelChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search targets.
        /// </summary>
        internal static string LabelSearchTargets {
            get {
                return ResourceManager.GetString("LabelSearchTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statuses.
        /// </summary>
        internal static string LabelStatuses {
            get {
                return ResourceManager.GetString("LabelStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load invites: {0}.
        /// </summary>
        internal static string MessageErrorLoadInvites {
            get {
                return ResourceManager.GetString("MessageErrorLoadInvites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not revoke invite: {0}.
        /// </summary>
        internal static string MessageErrorRevokeInvite {
            get {
                return ResourceManager.GetString("MessageErrorRevokeInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No invites found matching your criteria..
        /// </summary>
        internal static string MessageInfoNoInvites {
            get {
                return ResourceManager.GetString("MessageInfoNoInvites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Invites.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search targets....
        /// </summary>
        internal static string PlaceholderSearchTargets {
            get {
                return ResourceManager.GetString("PlaceholderSearchTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any option.
        /// </summary>
        internal static string SelectAccountAny {
            get {
                return ResourceManager.GetString("SelectAccountAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only with account.
        /// </summary>
        internal static string SelectAccountWith {
            get {
                return ResourceManager.GetString("SelectAccountWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only without account.
        /// </summary>
        internal static string SelectAccountWithout {
            get {
                return ResourceManager.GetString("SelectAccountWithout", resourceCulture);
            }
        }
    }
}
